FROM quay.io/aptible/debian:<%= ENV.fetch "DEBIAN_VERSION" %>

ENV MONGO_VERSION <%= ENV.fetch "MONGO_VERSION" %>
ENV MONGO_FLAVOR <%= ENV.fetch "MONGO_FLAVOR" %>
ENV MONGO_GPG_KEY <%= ENV.fetch "MONGO_GPG_KEY" %>
ENV TAG <%= ENV.fetch "TAG" %>

# Add MongoDB repository
ADD "${TAG}/templates/mongodb.list" /etc/apt/sources.list.d/mongodb.list
RUN apt-install gnupg && apt-key adv --keyserver keyserver.ubuntu.com --recv "$MONGO_GPG_KEY"

# Install MongoDB core
RUN apt-install adduser
ADD bin/install-mongodb.sh /install-mongodb.sh
RUN /install-mongodb.sh

# Install MongoDB tools and utilities we need
RUN apt-install "mongodb-${MONGO_FLAVOR}-tools=${MONGO_VERSION}" procps ca-certificates python pwgen

# Configuration
ENV DATA_DIRECTORY /var/db
ENV SSL_DIRECTORY /etc/ssl/mongo
RUN mkdir -p "${DATA_DIRECTORY}" "${SSL_DIRECTORY}"

# Tools
ADD bin/run-database.sh /usr/bin/
ADD bin/parse_mongo_url.py /usr/bin/
ADD bin/utilities.sh /usr/bin/
ADD bin/autotune /usr/local/bin/

ADD templates/mongo-scripts /mongo-scripts

# Unit tests (executed by test.sh)
ADD "${TAG}/test" /tmp/test
ADD test /tmp/test

VOLUME ["$DATA_DIRECTORY"]
VOLUME ["$SSL_DIRECTORY"]
EXPOSE 27017

ENTRYPOINT ["run-database.sh"]
